title:              LearnAWS
email:              contact@learnaws.com.bd
description:        A Blog To Educate AWS Cloud
author:             cat903
baseurl:            "cat903.github.io/"
url:                "learnaws"

# Social Profiles
twitter_username:   learnawsbd
github_username:    learnawsbd
facebook_username:  learnawsbd
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
